### ISSUE TITLE
People without bio don't get added to database since 0.3 update.

### ISSUE THREAD

**Issue by misentle** [Dutchie322/bclub-tools#25]
Bug only happens if player's bio have never been updated since account creation. Players with updated bios(even if it was changed to an empty string at least once) get added to database just fine.

**Comment by Dutchie322** [comment]
Ah, good catch! I've found the problem and fixed it in 6669878b4fcb7e7fce2e3192482ce10d31e4c9f3.

A fixed version (v0.3.1) has been submitted to the Chrome store for review and should be available soon.

Thanks for reporting!
