### ISSUE TITLE
Chat Rooms and Friends not being updated

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Dutchie322/bclub-tools#26]
Basically ever since I would say about the 11/04/2021 the extension has not been saving the chat log or updating friends for me. I think it happened with the most recent beta. Not sure what the cause could be so I can't give you much infomation.

All I know is that the other things work fine, like refreshing chat rooms notifying when friends come online etc. But the chat logging just doesn't work at all. I hope this can be resolved soon.

Ow yer I am on firefox if that makes any difference.

**Comment by Dutchie322** [comment]
Thanks for the report. I have to admit that I largely forgot about Firefox in testing, but I will look into it. As a temporary work-around, the extension still works as it should with Chromium-based browsers (Brave, Opera, Vivaldi, Edge, Chrome itself).

**Comment by Shiranui-Izayoi** [comment]
That is good to know. Don't use chrome much as not much of a fan of it sucking up ALL the memory. But still nice to know. Also just an FYI that I found. It is possible to upload/update it on the addon's for Firefox and have it be self signed. Then I THINK you can just distribute an update link for updates. That way Firefox users don't have to allways put it in their temporary addons every time they launch their browser.

**Comment by Dutchie322** [comment]
I've played around with the extension in Firefox, and it appears to be capturing chat logs and friend information correctly. One thing I did notice, however, was that when the log viewer is opened in a private window, nothing is displayed. This is accompanied by errors in the console, which look like permission errors when trying to access the internal database. When I open the log viewer in a normal window, everything loads correctly, even data from a private session.

Is this what happens for you as well?

On a side note, I'll look into getting the extension updated on the Firefox Add-Ons website. I have forgotten to do that for a long time, sorry about that.

**Comment by Shiranui-Izayoi** [comment]
Not really. I have my game open in a normal window but it isn't actually capturing the chat log and hasn't since the date I mentioned aka the 11th of this month.

I do use console on club but I don't think that would cause any issues. Since I think the scripts are injected differently. And it seems to happen even when no console is used.

It also won't export the datebase, if that means anything. It can detect when friends come online. But isn't logging people like it use to.

**Comment by Dutchie322** [comment]
Hmm, okay. I guess it doesn't show the size of the database then either. Is it possible that the database is quite large? Maybe it runs out of memory somewhere.

Also, do you have any other extensions that interact with the game? Like any wardrobe extensions or the Curse maybe?

**Comment by Shiranui-Izayoi** [comment]
Nope no wardrobe or curse. The datebase size is 28.1MB.

**Comment by Shiranui-Izayoi** [comment]
Hey just wanted to say this is still an issue. It isn't recording anything. Not even friends. It will show them in the right tab when the come on but it isn't recording people I meet or anything.

**Comment by Dutchie322** [comment]
Thanks for the update. Life got quite a bit busy for me as of late, so I didn't have time to look into this... at all.

Glad you managed to download the export, I'm aware that it gets really slow when the database grows beyond a few MB, and it's on my list for a redesign at some point.

I'll look into getting the extension back in the Firefox extension store. I wasn't aware that there was a demand for Firefox support~

**Comment by Dutchie322** [comment]
The import and export functionality have been reworked in the latest release, giving you a clearer picture what's going on. I've also provided an xpi for use in Firefox.

https://github.com/Dutchie322/bclub-tools/releases/tag/v0.4.0

**Comment by Shiranui-Izayoi** [comment]
Thanks dude this is great. And again thanks for the firefox XPI.

I will look forward to using it. Also while messing around I have found you can cut down on the amount of lines in the Manifest by using
```
		"*://*.bondageprojects.com/*",
		"*://*.bondageprojects.elementfx.com/*",
		"*://*.bondage-europe.com/*"
``` 
In matches replacing all the variants of the website name and also
```
	"http://*/*",
	"https://*/*"
```

In permissions again cutting down on the amount of lines. I found it in a different extension and tried it out and it seems to work great.

**Comment by Dutchie322** [comment]
Ah, that's useful, thanks for that! Adding it to a new issue concerning more Firefox manifest shenanigans: #41

**Comment by Shiranui-Izayoi** [comment]
> 
> 
> Ah, that's useful, thanks for that! Adding it to a new issue concerning more Firefox manifest shenanigans: #41

Yay glad I could help. This seems to work with all browsers so that is cool.
