### ISSUE TITLE
Firefox xpi

### ISSUE THREAD

**Issue by misentle** [Dutchie322/bclub-tools#32]
Hello. 

Can you make a signed xpi file for Firefox? Since there is no BCTools on the addon site for Firefox, it would be nice to have it at least as a signed xpi file so that Firefox users don't have to reinstall it every time they restart their browser.

**Comment by Dutchie322** [comment]
I'll look into getting it back on the Firefox addon site. I had the very first version on there once, with only one user, so I took it down at the time.

**Comment by Dutchie322** [comment]
The latest release has an xpi available. The options page doesn't work right now, I'll fix that soon.

https://github.com/Dutchie322/bclub-tools/releases/tag/v0.4.0
