### ISSUE TITLE
Search room refresh looses the current page

### ISSUE THREAD

**Issue by zorgjbe** [Dutchie322/bclub-tools#43]
Right now, enabling the autorefresh makes the lobby jump back to the first page when a refresh happens, even when there's not search term entered. This got me a bit confused, because I wasn't expecting that to happen, and with the right timing you can end up clicking on a completely unrelated first-page room. Just to clarify, the refresh is nice, even on a normal, "not searching" lobby, but reselecting the correct page on refresh (or the last one if it lost a page) would be ❤️.

**Comment by Dutchie322** [comment]
Really good point. The game has become way more popular as of late, making this an inconvenience 🙂

I'll see if I can do something about it.

**Comment by Dutchie322** [comment]
A new version has been published for review on the Chrome web store: v0.5.0. This includes a rewritten auto refresh of the chat rooms, which is disabled by default. It will also stop refreshing when you're looking at anything other than the first page of results.
