### ISSUE TITLE
Can't export if a chat log is corrupted

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Dutchie322/bclub-tools#54]
Basically if a chat room log gets corrupted for whatever reason then you are unable to export the files. Since the export can't read that log.

And since there is no way to delete individual chat logs then you are left with the only option being to delete the entire database.

Found this out after one log from a room got corrupted causing it to never load when clicked on. I then tried to export just for it to get stuck near the end. And as far as I can tell it is impossible to remove the data causing the issue.

Also might I suggest making an export option that only exports the chatlogs and not the member images etc?

**Comment by Dutchie322** [comment]
Interesting... in what way can a log get corrupted? Do you see any error in the console when trying to open that corrupted chat log?

And yes, it's about time to add more tools to manage the data that's being stored... it can grow a lot over time. Sadly, I haven't had time to give this extension the attention it needs lately.

Also good suggestion regarding extra options on what gets exported.

**Comment by Shiranui-Izayoi** [comment]
It just kept loading forever. Like I would click on the log and it would just load and load and load. Not sure how it got corrupted but it did. When I tried to look into the data saved on the disk it was just "person:" with no text in it.

And I didn't see anything in the console IIRC.

**Comment by Dutchie322** [comment]
A new version has been published for review on the Chrome web store: v0.5.0. I've made exporting the images optional, and it's now possible to remove all images from the database without touching the rest of the data. Not sure if it will help with the corrupted chatlog, I plan on adding more controls to delete specific sessions later. I've created a separate issue for that: #68
