### ISSUE TITLE
the tools frequently crash

### ISSUE THREAD

**Issue by Shin-Gojira** [Dutchie322/bclub-tools#62]
the extension has been crashing a lot and this is the best one available for a chat logger

**Comment by Dutchie322** [comment]
Thanks for reaching out. I'm getting messages left and right that people do seem to prefer the logging capabilities of this extension. I've been thinking about alternative ways of publishing this functionality. I don't want to deal with the Chrome Web Store anymore though (or really with Google/Alphabet as a whole), so I'll do some experiments and see if I can make it work.

There's also the matter of browsers simply not being able to deal with the amount of data this extension generates, so I'm thinking of introducing an automatic cleanup function... deleting data older than a week or month or so.

No promises, but I'm slightly more motivated to keep this going.

**Comment by Dutchie322** [comment]
A new version has been published for review on the Chrome web store: v0.5.0. A lot of problems were addressed in this release; I removed a lot of the errors that popped up during use of this extension.
