### ISSUE TITLE
Crash on R111 beta

### ISSUE THREAD

**Issue by zorgjbe** [Dutchie322/bclub-tools#82]
Crash happens here: https://github.com/Dutchie322/bclub-tools/blob/dec44c97dc3c838539d5c5b4b718f3cbbfa9b431/projects/content-script/src/user-input-listener.ts#L46
The issue is that the new assets from the new upper body groups are named "" (so that they have a consistently generated layer name). But "" is falsy, so the extension peeks at a possible `Asset` and breaks.

**Comment by Dutchie322** [comment]
Thanks for the report!
